### ISSUE TITLE
Project structure not compatible with Arduino library specification

### ISSUE THREAD

**Issue by vzahradnik** [JSC-electronics/adeon-embedded#1]
In order to be included in Arduino Library Manager, we must adhere to their [specification](https://github.com/arduino/Arduino/wiki/Arduino-IDE-1.5:-Library-specification).

@Ales-Svoboda Finish implementation of base functionality and then I will help you to make necessary changes in order to make the code compatible.

**Comment by Ales-Svoboda** [comment]
Resolved in 16810ea.
